### ISSUE TITLE
The new version of Zotero7(beta55+) do not display TLDR the right way.

### ISSUE THREAD

**Issue by baker221** [syt2/Zotero-TLDR#6]
<img width="333" alt="Snipaste_2024-01-31_00-10-03" src="https://github.com/syt2/Zotero-TLDR/assets/43471538/fe577bf2-a22f-4cdb-a958-d8bd6feccf57">

The new version of Zotero7 has new interface, which cannot display the full content *TLDR*. Is there any idea to deal with this?

**Comment by llity** [comment]
![image](https://github.com/syt2/Zotero-TLDR/assets/11771112/92c78d9e-9ed4-4b81-bb33-9d0d3dc61a6c)
没有对齐wen b文本

**Comment by llity** [comment]
目前好像只有extra不限制高度？，其他info都是显示一行。

**Comment by llity** [comment]
可以考虑增加一个笔记功能开关，谢谢，才发现这么好用

**Comment by llity** [comment]
和最新测试版不兼容，软件会崩溃
